add test statistics

diff --git a/.github/workflows/integrationtest.yaml b/.github/workflows/integrationtest.yaml
--- a/.github/workflows/integrationtest.yaml
+++ b/.github/workflows/integrationtest.yaml
@@ -90,6 +90,15 @@ jobs:
           rm ${HOME}/.ocmconfig
         fi
         pytest ./tests
+        res=$?
+        now=$(date +"%Y-%m-%d %H:%M:%S%z")
+        if [ ${res} -eq  0 ]; then
+          echo "Tests run successfully."
+          echo "$now | passed" >> README.md
+        else
+          echo "Tests failed."
+          echo "$now | failed" >> README.md
+        fi
     - name: stop docker registry
       if: always()
       run: |
@@ -103,6 +112,6 @@ jobs:
         commit-message: 'add test report'
         force-add: 'true'
         rebase: 'true'
-        files: docs/
+        files: README.md docs/
         name: github-ation
         email: noreply@github.com
