add getting fqdn fallback

diff --git a/.github/workflows/integrationtest.yaml b/.github/workflows/integrationtest.yaml
--- a/.github/workflows/integrationtest.yaml
+++ b/.github/workflows/integrationtest.yaml
@@ -26,6 +26,11 @@ jobs:
         echo "home-dir: $HOME"
         echo "fqdn hostame is: $FDQN_NAME"
         if [ "$FDQN_NAME" = "$HNAME" ]; then
+          echo "Failed to get fully qualified hostname: $FQDN_NAME, using python"
+          FDQN_NAME=`python -c "import socket; print(socket.getfqdn())"`
+          exit 1
+        fi
+        if [ "$FDQN_NAME" = "$HNAME" ]; then
           echo "Failed to get fully qualified hostname: $FQDN_NAME"
           exit 1
         fi
